name: libdsp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - libstdcxx-ng
  - numpy
  - ipython
  - matplotlib
  - networkx
  - opencv
  - pip:
    - -e .
    - dearpygui
  - black
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
